#include <string_view>

#include "imperivm/core/script/host.hpp"

// The shipped host surface, declared and unimplemented.
//
// GENERATED by walking the ASTs of all **885** `.vs` files in the retail
// install: **271 free-function entry points** and **555 member entry points**,
// plus the 245 global constants and ambient globals.
//
// Declaring the lot up front is what makes the failure mode right. A script
// that calls something nobody has written yet stops with "host entry point
// SetPlayerStatus/3 is declared but not implemented" rather than with a
// plausible zero that drifts the simulation off course a thousand ticks later,
// and Part 5 fills entries in with `define()` alone -- no new names, no new
// arities, nothing reshaped.
//
// ## The 577 that used to be the whole corpus, and the 308 that were missing
//
// This file was for a long time generated from `docs/formats/vs-host-api.md`
// alone, which is generated from the **577** `.vs` files in `data.pak`. That is
// 205 free entry points and 542 member entry points -- and it is not the whole
// surface. The other **308** shipped `.vs` files live inside the 24 `.bfhp`
// containers (13 adventures, the conquest, the scenarios), which no pack
// carries, and between them they use **66 free entry points and 13 member
// entry points that appear nowhere in `data.pak`** -- 3,392 and 380 call sites
// respectively. `WaitSettlementCapture/3`, `RunAIHelper/4` (285 sites),
// `IsAIHelperRunning/1` (236), `SpawnGroup/1` (181), `GiveNote/1`, `RunConv/1`,
// `PlayMovie/1`, `DiplCeaseFire/3` -- the whole campaign layer. Every one of
// them read as an *unknown call* rather than a named trap, which is exactly the
// failure mode this file exists to prevent.
//
// Six names are worse than missing: they are present at one arity and used at
// another. `EndGame` is declared `/2` by the signature registrar and called
// `/3` at all 61 container sites; `EnvReadInt`, `EnvReadString`, `EnvWriteInt`
// and `EnvWriteString` each have a container-only form one argument shorter --
// the root scope -- with 403 sites between them; and the member `InHolder` is
// `/0` in `data.pak` (`Unit::InHolder`) and `/1` in the containers
// (`ObjList::InHolder(str)`, `Query::InHolder(str)`, registered at 0x00563755
// and 0x0057b0f1).
//
// The count read five until a second pass covered members as well as free
// functions. The member half of this comparison is the easy one to skip,
// because members are the half nobody thinks of as "the API".
//
// ## The evidence, with a control
//
// All **65** container-only free-function names occur in `gbr.exe`'s string
// pool as standalone null-terminated strings; all **13** member names occur
// there in the `Receiver::Method` form the member registrar uses
// (`Unit::AddBonus`, `ObjList::RemoveFromGroup`, `Conversation::SetActor`,
// `Settlement::AllowCapture`, `Query::NearestObj`, ...). The control: **0 of 60**
// randomly sampled map-declared object names (`NO_*`, `Q_*`, `T_*`) occur in the
// binary at all. 65/65 against 0/60 is what makes these engine surface rather
// than content.
//
// Regenerating: parse every `.vs` in `corpus.pack_paths()` and
// `corpus.container_paths()` with `vs_parse.Inventory`, fold `NO_PARENS` (-1)
// into arity 0, and take `functions` and `methods`. Do **not** take
// `bare_names` from the containers: 611 of them are map-declared scriptobj
// bindings, not globals, and the same control says so.

namespace imperivm::core::script {
namespace {

struct Declaration {
  const char* name;
  std::uint16_t arity;
};

constexpr Declaration kFreeFunctions[] = {
    {"AIBreakScript", 1}, {"AIGetPlayer", 0}, {"AIRun", 1}, {"AIRun", 5}, {"AIStart", 3},
    {"AIStop", 1}, {"AIVar", 2}, {"AIVar", 3}, {"AllyMilEval", 1}, {"AreaAIMaxPriority", 3},
    {"AreaAINoRecruit", 3}, {"AreaAISetAttackOptimism", 3}, {"AreaCenter", 1}, {"AreaDistTo", 2},
    {"AreaObjs", 2}, {"ArenaTrainCmd", 1}, {"ArenaUTech", 1}, {"ArenaUType", 1}, {"AttackArea", 2},
    {"AttackSetForTraining", 3}, {"BlockUserInput", 0}, {"Breakpoint", 0}, {"CLAMP", 3},
    {"CheckLsaPath", 3}, {"CheckUEnabled", 5}, {"Choose", 2}, {"Choose", 3},
    {"ClassPlayerAreaObjs", 3}, {"ClassPlayerObjs", 2}, {"ClearDebug", 0}, {"ClearDiplomacy", 0},
    {"ClearNotes", 0}, {"ClearSelection", 1}, {"ClrShipNeeds", 2}, {"ConquestBonus", 0},
    {"ControllableObjs", 2}, {"ConvResult", 1}, {"Count", 2}, {"CreateFeedback", 2},
    {"DiplAreAllied", 2}, {"DiplCeaseFire", 3}, {"DiplGetCeaseFire", 2},
    {"DiplGetShareControl", 2}, {"DiplGetShareSupport", 2}, {"DiplGetShareView", 2},
    {"DiplShareControl", 3}, {"DiplShareSupport", 3}, {"DiplShareView", 3}, {"Dist", 2},
    {"EndConvSetup", 2}, {"EndGame", 2}, {"EndGame", 3}, {"EnemyInRange", 3}, {"EnemyMilEval", 1},
    {"EnemyObjs", 2}, {"EnemyPlayersEval", 4}, {"EnvReadInt", 1}, {"EnvReadInt", 2},
    {"EnvReadObj", 2}, {"EnvReadString", 1}, {"EnvReadString", 2}, {"EnvWriteInt", 2},
    {"EnvWriteInt", 3}, {"EnvWriteObj", 3}, {"EnvWriteString", 2}, {"EnvWriteString", 3},
    {"Eval", 6}, {"EvalGroup", 1}, {"ExploreAll", 0}, {"ExploreArea", 2}, {"ExploreCircle", 3},
    {"FindRuins", 3}, {"FindTeleport", 3}, {"FormDescription", 1}, {"FriendlyObjs", 2},
    {"GAIKACount", 0}, {"GetAngleByDir", 1}, {"GetCatapultAttackPoint", 1}, {"GetClassRace", 1},
    {"GetCmdCost", 3}, {"GetCmdStaminaCost", 1}, {"GetConst", 1}, {"GetConstStr", 1},
    {"GetCounterUnits", 2}, {"GetDifficulty", 0}, {"GetDirByAngle", 1}, {"GetGAIKA", 1},
    {"GetInnState", 1}, {"GetMapRect", 0}, {"GetNamedObj", 1}, {"GetPlayerRace", 1},
    {"GetPlayerUnits", 1}, {"GetPlayerUnits", 2}, {"GetRaceStr", 1}, {"GetRaceStrPref", 1},
    {"GetRandomHeroClass", 2}, {"GetRandomPointInArea", 1}, {"GetResearchHack", 0},
    {"GetSelection", 0}, {"GetSettlement", 1}, {"GetSettlements", 2}, {"GetSpeed", 0},
    {"GetSquad", 2}, {"GetTeamMilitaryScore", 1}, {"GetTeamOverallScore", 1},
    {"GetTerrainHeight", 1}, {"GetTime", 0}, {"GetTrainGold", 1}, {"GetUseCount", 0},
    {"GetVec", 3}, {"GetVecByDir", 2}, {"GiveNote", 1}, {"Group", 1}, {"HasStarvingArmy", 1},
    {"HeroArmiesFullPerc", 1}, {"HeroSkillId", 1}, {"HideAnnouncement", 1}, {"HideZoomMap", 0},
    {"IdxToSet", 1}, {"IncShipNeeds", 2}, {"Intersect", 2}, {"InvalidateDamageFormulaParams", 0},
    {"InvalidateRegenConsts", 0}, {"IsAIHelperRunning", 1}, {"IsAIPlayer", 1}, {"IsExplored", 2},
    {"IsFinished", 1}, {"IsMultiplayer", 0}, {"IsNoteActive", 1}, {"IsPassable3x3", 1},
    {"IsPointInWater", 1}, {"IsProtected", 3}, {"IsResearched", 2}, {"IsResearching", 2},
    {"IsRunning", 1}, {"IsSelectionAssigned", 1}, {"IsWaiting", 1}, {"IsWaterLsa", 1},
    {"ItemUsed", 1}, {"KillScript", 0}, {"LAIKA", 2}, {"ListFolder", 1}, {"ListFolderEx", 2},
    {"LockView", 0}, {"MAX", 2}, {"MIN", 2}, {"MapName", 0}, {"MapSize", 0}, {"MaxSetIdx", 0},
    {"MilEval", 1}, {"MilUnits", 1}, {"MoveToArea", 2}, {"NearestHospital", 1},
    {"NearestStronghold", 2}, {"NearestStronghold", 3}, {"NumSquads", 1}, {"ObjsInCircle", 3},
    {"ObjsInRange", 3}, {"ObjsInSight", 2}, {"OnLeft", 2}, {"Outposts", 1}, {"ParseStr", 2},
    {"Party", 0}, {"PartyQuery", 0}, {"Pause", 0}, {"Place", 3}, {"PlaceCatapult", 4},
    {"PlayMovie", 1}, {"PlaySound", 1}, {"PlaySound", 2}, {"Point", 2},
    {"PrepareAiTransportShip", 5}, {"ProfileStart", 0}, {"ProfileStop", 0}, {"RUType", 2},
    {"RandomOffset", 1}, {"RemoveNote", 1}, {"RevealHiddenEnemyUnits", 3}, {"Run", 1},
    {"RunAIHelper", 4}, {"RunConv", 1}, {"RunSequence", 1}, {"SPFCalcConnectHighRes_Quant", 0},
    {"SPFDone", 0}, {"SPFFindAreas_Quant", 0}, {"SPFIncreaseConnect", 0},
    {"SPFIncreaseConnect_Quant", 0}, {"SPFInitConnectData", 0}, {"SPFInitData", 0},
    {"SPFInitDirectionData", 0}, {"SPFInitPointToAreaData", 0}, {"SS_STR", 1}, {"SelAvgFood", 0},
    {"SelAvgLevel", 0}, {"SelAvgStamina", 0}, {"SelHealth", 0}, {"SelMaxHealth", 0},
    {"SetAIVar", 3}, {"SetExperienceModifier", 2}, {"SetFog", 1}, {"SetGlobalBloodlust", 1},
    {"SetInnState", 2}, {"SetMAIKA", 3}, {"SetNoAIFlag", 2}, {"SetPlayerStatus", 3},
    {"SetPlayerStatus", 4}, {"SetShortcutSel", 3}, {"SetSpeed", 1}, {"SetTerritoryState", 2},
    {"SettlementCount", 3}, {"ShipNeeds", 2}, {"Ships", 2}, {"ShowAnnouncement", 2},
    {"ShowHint", 3}, {"ShowTutorial", 3}, {"Sleep", 1}, {"SpawnGroup", 1},
    {"SpawnGroupInHolder", 2}, {"SpawnNamed", 1}, {"Squadize", 3}, {"StartPlayerScript", 2},
    {"StarvingArmyPos", 1}, {"StopAIHelper", 1}, {"Str2Int", 1}, {"StrLen", 1}, {"StrMid", 3},
    {"Strongholds", 1}, {"Substract", 2}, {"Subtract", 2}, {"SwapSelectedObj", 2},
    {"TempleUTrain", 1}, {"TempleUType", 1}, {"Translate", 1}, {"Translatef", 2},
    {"Translatef", 3}, {"UEnabled", 2}, {"UTech", 2}, {"UTrainCmd", 2}, {"UType", 2},
    {"UnblockUserInput", 0}, {"Union", 2}, {"UnitsAroundSettlement", 2}, {"UnitsInSettlement", 2},
    {"UnlockView", 0}, {"UserNotification", 4}, {"View", 2}, {"ViewPos", 0},
    {"VisibleObjsInSight", 2}, {"WaitCommonObjects", 3}, {"WaitConvRequest", 3},
    {"WaitConvRequest", 5}, {"WaitEmptyQuery", 2}, {"WaitEnvIntBetween", 4},
    {"WaitHealthBetween", 4}, {"WaitIdle", 2}, {"WaitNonEmptyQuery", 2}, {"WaitObjInQuery", 3},
    {"WaitQueryCountBetween", 4}, {"WaitSettlementCapture", 3}, {"WaitUnitsInArea", 3},
    {"WasSelectionAssigned", 1}, {"_GetSelection", 0}, {"_PlaceEx", 4},
    {"_ZoomMapLastShownTime", 0}, {"abs", 1}, {"cls", 0}, {"pr", 1}, {"rand", 1}, {"rollover", 2},
    {"rollover", 3}, {"rollover_desc", 3},
    // `selu` is the one console global a shipped map reaches for -- twice, as
    // an object, in `5_Great_Battles_Britain`'s `Maps/3/Sequences/seq8.vs` --
    // and `gbr.exe` registers it as a zero-argument `Unit` accessor (the
    // textual registration at 0x006aa986, signature `Unit`, body 0x006a66b0)
    // beside its seven siblings `selg selsq sels selb selh selo sel`. A bare
    // name the compiler cannot resolve as a global is a trap on the first
    // pass of that loop, which is the whole of the map's timed narration.
    // The siblings have no site and stay undeclared. See `sim/orders.cpp`.
    {"selu", 0},

};

constexpr Declaration kMembers[] = {
    {"AI", 0}, {"AIDest", 0}, {"AIGetSkillToDevelop", 2}, {"AIRun", 1}, {"AIRun", 2}, {"Add", 1},
    {"AddBonus", 5}, {"AddCommand", 2}, {"AddCommand", 3}, {"AddCommandOffset", 3},
    {"AddDruid", 2}, {"AddItem", 1}, {"AddList", 1}, {"AddMaxSentries", 1}, {"AddSentries", 1},
    {"AddToGroup", 1}, {"AddToMaxPopulation", 1}, {"AddToPopulation", 1}, {"AddToStoreBin", 0},
    {"AddUnit", 1}, {"AdjustFlyDir", 1}, {"AllEnemiesInHolder", 1}, {"AllowCapture", 1},
    {"ApplyAiTransport", 0}, {"ApproachingSquads", 2}, {"AreEnemiesAround", 0},
    {"AreFriendsAround", 0}, {"AreUnitsToBoard", 0}, {"AsBarrack", 0}, {"AsBuilding", 0},
    {"AsCatapult", 0}, {"AsDruid", 0}, {"AsFlying", 0}, {"AsGate", 0}, {"AsHero", 0},
    {"AsItemHolder", 0}, {"AsSacrifice", 0}, {"AsShip", 0}, {"AsTeleport", 0}, {"AsTower", 0},
    {"AsUnit", 0}, {"AsWagon", 0}, {"AttachTo", 1}, {"Attack", 1}, {"AttackWait", 0},
    {"AvailableSkillPoints", 0}, {"BestArena", 0}, {"BestBarrack", 1}, {"BestCandidateToBoard", 0},
    {"BestGate", 1}, {"BestMDPos", 5}, {"BestNoIndependentTargetInSquadSight", 0},
    {"BestProtPos", 4}, {"BestTarget", 0}, {"BestTargetForPos", 0}, {"BestTargetInGAIKA", 0},
    {"BestTargetInRange", 2}, {"BestTargetInSquadSight", 0}, {"BestTargetInSquadSight", 1},
    {"BestTargetInSquadSightExclusive", 1}, {"BestTargetInSquadSightMisZeroDamage", 0},
    {"BestTargetInSquadSight_PreferUndiseased", 0}, {"BestTemple", 0}, {"BestToSupply", 0},
    {"BestTrainingTarget", 0}, {"BoardUnit", 1}, {"Buildings", 0}, {"CalcEscapeDirection", 0},
    {"CalcGoAround", 0}, {"CalcPriority", 1}, {"CanAfford", 1}, {"CanAfford", 2}, {"CanAttack", 1},
    {"CanBeCaptured", 0}, {"CanExplore", 1}, {"CanResearch", 1}, {"CanSee", 1},
    {"CancelArmyBoard", 0}, {"CancelEfcUpgrade", 0}, {"Center", 0}, {"CheckTechBudget", 2},
    {"ClampToMap", 0}, {"Clear", 0}, {"ClearAiTransport", 0}, {"ClearCommands", 0},
    {"ClearDamageTaken", 0}, {"ClearDead", 0}, {"ClearTarget", 0}, {"ClearTowerTarget", 0},
    {"ClipDestToMap", 1}, {"CloseNow", 0}, {"ClrCmd", 3}, {"CmdCount", 0}, {"CmdCount", 1},
    {"CmdDisable", 1}, {"Consume", 3}, {"Contains", 1}, {"ControlledNeighbors", 1}, {"Count", 0},
    {"Count", 1}, {"Count", 3}, {"Count", 6}, {"CoverOfMercyAction", 0}, {"CreateBoatFood", 1},
    {"CreateBoatGold", 1}, {"CreateMuleFood", 1}, {"CreateMuleGold", 1}, {"CreateShip", 1},
    {"Cur", 0}, {"Curse", 0}, {"Damage", 1}, {"DecreaseLoyalty", 1}, {"DelOrder", 0},
    {"DelSentry", 0}, {"Deselect", 0}, {"DestGAIKA", 0}, {"DetachArmy", 0}, {"DetachFrom", 1},
    {"Disappear", 0}, {"Disease", 0}, {"Dist", 1}, {"DistTo", 1}, {"DoCarryNothing", 0},
    {"DonateFood", 1}, {"DropItem", 2}, {"EOL", 0}, {"EconomyScript", 0}, {"Empty", 0},
    {"EnemiesInSight", 0}, {"EnterHolder", 1}, {"Erase", 0}, {"Eval", 0}, {"Eval", 2}, {"Eval", 3},
    {"Eval", 6}, {"EvalAttach", 2}, {"EvalNeighbors", 6}, {"EvalSentries", 0}, {"ExchangeItem", 2},
    {"ExecCmd", 4}, {"ExecDefaultCmd", 4}, {"ExitHolder", 1}, {"Explored", 1}, {"Face", 1},
    {"FilterClosest", 2}, {"FindItem", 1}, {"FindNearBird", 0}, {"FindNearEnterExit", 1},
    {"FindPointToStay", 0}, {"FindResearchLab", 1}, {"FindUnitBelowILevel", 1},
    {"FindUnitToHeal", 0}, {"FindUnitToHide", 0}, {"FindUnitToLearn", 0},
    {"FindUnitToRevitalize", 0}, {"FoodComing", 0}, {"ForceAddUnit", 1}, {"ForceIdle", 0},
    {"FormAcceptMove", 0}, {"FormKeepMoving", 1}, {"FormPathLeft", 0}, {"FormRadius", 0},
    {"FormSetupAndMoveTo", 4}, {"GAIKAIn", 0}, {"GetAIControlledUnits", 4}, {"GetAnim", 0},
    {"GetAnimDuration", 1}, {"GetAnimTime", 1}, {"GetAverageDirection", 0},
    {"GetBestCrippleTarget", 0}, {"GetBestCurseTarget", 0}, {"GetCanExecCmd", 1},
    {"GetCentralBuilding", 0}, {"GetCommanded", 0}, {"GetControlFlag", 1}, {"GetCurrentTarget", 0},
    {"GetDefenderCls", 1}, {"GetDefendersMax", 1}, {"GetDefendersOut", 1}, {"GetDestPoint", 1},
    {"GetDir", 0}, {"GetDistToPlayers", 4}, {"GetEconomyScript", 1}, {"GetEndLevel", 1},
    {"GetEnterExit", 0}, {"GetEnterPoint", 1}, {"GetExitPoint", 2}, {"GetExitVector", 0},
    {"GetFinalPartyOrientation", 0}, {"GetFlags", 1}, {"GetGAIKA", 0}, {"GetGaika", 0},
    {"GetHolderSett", 0}, {"GetItem", 1}, {"GetJupiterAngerTarget", 0}, {"GetLastAttacker", 0},
    {"GetLoan", 0}, {"GetMaxSentries", 0}, {"GetNumSentries", 0}, {"GetNumSentrySlots", 0},
    {"GetObjList", 0}, {"GetOutpostFood", 0}, {"GetParryMode", 0}, {"GetParty", 0},
    {"GetPoint", 2}, {"GetPointOnTarget", 1}, {"GetPriority", 1}, {"GetSacrifice", 0},
    {"GetSentry", 0}, {"GetSentryClassName", 0}, {"GetShipToBoard", 0}, {"GetSkill", 1},
    {"GetSquad", 0}, {"GetSquads", 3}, {"GetSquads", 4}, {"GetStaminaDecTime", 0},
    {"GetStartLevel", 1}, {"GetStrat", 1}, {"GetTacticScript", 1}, {"GetTransPt", 0},
    {"GetUITarget", 0}, {"GetUnexploredPoint", 1}, {"GetUnitsInSameHolder", 0},
    {"GetUnitsOnBoard", 0}, {"GiveItem", 2}, {"GlobalSpellStart", 2}, {"GlobalSpellStop", 0},
    {"GoldConverted", 1}, {"GoldSpent", 1}, {"Goto", 4}, {"Goto", 5}, {"GotoAttack", 3},
    {"GotoAttack", 4}, {"GotoEnter", 5}, {"HasAiTransport", 0}, {"HasArmy", 0},
    {"HasFinalPartyOrientationRequest", 0}, {"HasFreedom", 0}, {"HasItem", 1}, {"HasPath", 0},
    {"HasSpecial", 1}, {"Heal", 1}, {"HealStamina", 1}, {"ID", 0}, {"Idle", 0}, {"Idle", 1},
    {"IdleAllGates", 0}, {"InHolder", 0}, {"InHolder", 1}, {"InRange", 1}, {"InRect", 1},
    {"InShip", 0}, {"IncKills", 1}, {"Init", 1}, {"Inside", 1}, {"IntoRect", 1},
    {"InvadeThroughGate", 2}, {"IsAlive", 0}, {"IsAlly", 1}, {"IsArmyOutside", 0}, {"IsBroken", 0},
    {"IsBuilding", 0}, {"IsBuilt", 0}, {"IsCentralBuliding", 0}, {"IsCity", 0}, {"IsCursed", 0},
    {"IsDead", 0}, {"IsDiseased", 0}, {"IsEmpty", 0}, {"IsEnemy", 1}, {"IsEnemyInSquadSight", 0},
    {"IsFull", 0}, {"IsHeirOf", 1}, {"IsHeroArmyFull", 0}, {"IsInAir", 0}, {"IsInState", 0},
    {"IsIndependent", 0}, {"IsIndependentGuarded", 0}, {"IsInvisibility", 0}, {"IsMilitary", 0},
    {"IsOutpost", 0}, {"IsOwn", 1}, {"IsPeaceful", 0}, {"IsPeasantAmbient", 0}, {"IsRam", 0},
    {"IsRanged", 0}, {"IsSentry", 0}, {"IsShipyard", 0}, {"IsStonehengeControlable", 0},
    {"IsStronghold", 0}, {"IsSummoningDeath", 0}, {"IsTTent", 0}, {"IsTeutonTent", 0},
    {"IsValid", 0}, {"IsValidCaptureTarget", 1}, {"IsValidTarget", 1}, {"IsVeryBroken", 0},
    {"IsVillage", 0}, {"IsVisible", 0}, {"IsWaterUnit", 0}, {"KillCommand", 0}, {"LSA", 0},
    {"LastFightTime", 0}, {"LastSeen", 1}, {"Leader", 0}, {"Len", 0}, {"LoadFood", 1},
    {"LoadGold", 1}, {"Lock", 0}, {"LookAround", 1}, {"MagicActionEnd", 0}, {"MaxAffordCount", 1},
    {"MaxNeed", 4}, {"MilitaryPresence", 1}, {"MinNeed", 4}, {"MistAction", 1},
    {"MostDamagedBuilding", 0}, {"Mutate", 1}, {"NearestObj", 1}, {"Next", 0}, {"No", 0},
    {"NoAttack", 1}, {"NoRecruit", 1}, {"NotifyBoardUnit", 1}, {"NotifyBoardUnitCancel", 1},
    {"NotifyShipBoardingCancel", 0}, {"NumGates", 0}, {"NumUnitsToBoard", 0}, {"ObjAlly", 1},
    {"ObjClass", 1}, {"ObjEnemy", 1}, {"ObjInjured", 0}, {"ObjectsAround", 1}, {"OpenAllGates", 0},
    {"OpenItemHolder", 1}, {"OpenNow", 0}, {"OrderDest", 0}, {"PathDestFound", 0}, {"PathTo", 3},
    {"PickFlyingPoint", 1}, {"PickLandingPoint", 1}, {"PlayAnim", 2}, {"PlayAnim", 3},
    {"PlaySound", 1}, {"Player", 0}, {"PopTransportationUI", 0}, {"PopulationDied", 0},
    {"Prioritized", 1}, {"Progress", 0}, {"Progress", 1}, {"PutItem", 2}, {"PutSentry", 0},
    {"RRepair", 0}, {"RamBestTarget", 0}, {"RecalcBonuses", 0}, {"Recruit", 4}, {"Remove", 1},
    {"RemoveFromAllGroups", 0}, {"RemoveFromGroup", 1}, {"RemoveFromStoreBin", 0},
    {"RemoveItem", 1}, {"RemoveItemsOfType", 1}, {"RemoveList", 1}, {"RepairAll", 0},
    {"RepayLoan", 0}, {"Research", 1}, {"ReserveFor", 2}, {"Revealed", 1}, {"Rewind", 0},
    {"Rot", 1}, {"RotateTo", 1}, {"Run", 0}, {"RunEconomyScript", 1}, {"RunStrat", 2},
    {"RunTacticScript", 1}, {"SameHolderAs", 1}, {"Select", 1}, {"SendFoodWagon", 2},
    {"SendTo", 2}, {"Set", 2}, {"SetActor", 2}, {"SetAutocast", 1}, {"SetBuildFrame", 1},
    {"SetBuilt", 0}, {"SetCarryGoodsAnim", 0}, {"SetCarryWaterAnim", 0}, {"SetCmd", 4},
    {"SetCmd", 5}, {"SetCmdEnable", 1}, {"SetCommand", 1}, {"SetCommand", 2},
    {"SetCommandOffset", 2}, {"SetCommanded", 1}, {"SetControlFlag", 2}, {"SetDebug", 1},
    {"SetEntering", 1}, {"SetExperience", 1}, {"SetFeeding", 1}, {"SetFinalPartyOrientation", 1},
    {"SetFood", 1}, {"SetFoodProduction", 1}, {"SetFormation", 1}, {"SetGold", 1},
    {"SetHealth", 1}, {"SetJupiterAngerTarget", 1}, {"SetLastAttackTime", 0}, {"SetLen", 1},
    {"SetLevel", 1}, {"SetLoan", 1}, {"SetLoyalty", 1}, {"SetMessengerStatus", 1},
    {"SetMinimapFlag", 1}, {"SetName", 1}, {"SetNoAIFlag", 1}, {"SetNoselectFlag", 1},
    {"SetParryMode", 1}, {"SetPlayer", 1}, {"SetPopulation", 1}, {"SetPos", 1}, {"SetPriority", 2},
    {"SetSight", 1}, {"SetSkill", 2}, {"SetSpeedFactor", 1}, {"SetStamina", 1}, {"SetState", 1},
    {"SetSummoningDeath", 1}, {"SetTarget", 1}, {"SetUITarget", 1}, {"SetUseCount", 1},
    {"SetUser", 1}, {"SetVisible", 1}, {"SetWalkAnim", 0}, {"SetWalkAnim", 1},
    {"ShowBuildAnimation", 1}, {"Siege", 3}, {"Siege", 4}, {"Size", 0}, {"SkillInEffect", 1},
    {"SneakCommand", 1}, {"SpentGoldOnArmy", 1}, {"SpentGoldOnTech", 1}, {"SrcGAIKA", 0},
    {"StartAnim", 2}, {"StartDelayedAnim", 3}, {"StartSupplyFood", 1}, {"StartTraining", 0},
    {"State", 0}, {"StateTime", 0}, {"StonehengeNumControllingMages", 0}, {"Stop", 1},
    {"StopReserving", 0}, {"StopSupply", 0}, {"StopTraining", 0}, {"StratRunning", 1},
    {"SupplyCount", 1}, {"TSAdvHeroSkills", 2}, {"TSArenaRecruit", 1}, {"TSGetAllArenae", 0},
    {"TSGetAllBarracks", 0}, {"TSGetAllTemples", 0}, {"TSRecruitArmy", 2}, {"TSRecruitHero", 0},
    {"TSResearch", 1}, {"TSTempleRecruit", 1}, {"TacticScript", 0}, {"TakeNearbyItems", 1},
    {"Taunt", 1}, {"TestFlags", 1}, {"TimePastLastAttack", 0}, {"TimeToActionMoment", 0},
    {"TimeToAnimFinish", 0}, {"TimeWithoutAttack", 0}, {"TimeWithoutWalking", 0}, {"Train", 5},
    {"TrainAttack", 1}, {"Traverse", 1}, {"UnboardAllUnits", 0}, {"UnboardUnits", 1}, {"Units", 0},
    {"UnitsCount", 0}, {"UnitsInHolderEval", 0}, {"UnitsMax", 0}, {"Unlock", 0},
    {"UpgradeBestBarrack", 1}, {"UpgradeEfc", 0}, {"UseItem", 1}, {"UseSkill", 1},
    {"UseTeleport", 4}, {"WaterLsa", 0}, {"_LastSelectionTime", 0}, {"amount", 0}, {"army", 0},
    {"attack", 0}, {"autocast", 0}, {"bottom", 0}, {"class", 0}, {"cmddelay", 0}, {"command", 0},
    {"command", 1}, {"count", 0}, {"dest", 0}, {"destination", 0}, {"dir", 0}, {"exit_vector", 0},
    {"experience", 0}, {"food", 0}, {"formation", 0}, {"gold", 0}, {"health", 0}, {"height", 0},
    {"hero", 0}, {"inherentlevel", 0}, {"item_count", 0}, {"itemtypes", 0}, {"left", 0},
    {"level", 0}, {"levelperitem", 0}, {"loan", 0}, {"loyalty", 0}, {"max_items", 0},
    {"max_population", 0}, {"max_units", 0}, {"maxarmy", 0}, {"maxfood", 0}, {"maxhealth", 0},
    {"maxstamina", 0}, {"minlevel", 0}, {"name", 0}, {"obj", 0}, {"player", 0}, {"population", 0},
    {"pos", 0}, {"posRH", 0}, {"race", 0}, {"raceStr", 0}, {"raceStrPref", 0},
    {"raceStrPrefLow", 0}, {"radius", 0}, {"range", 0}, {"restype", 0}, {"right", 0},
    {"script", 0}, {"settlement", 0}, {"sight", 0}, {"size", 0}, {"speed", 0}, {"stamina", 0},
    {"supplied", 0}, {"top", 0}, {"use_count", 0}, {"user", 0}, {"width", 0}, {"x", 0}, {"y", 0},
    {"z", 0},

};

/// Bare names that are neither locals nor parameters. Informational: the VM
/// asks `Host::global` for the value, and this is the list of things it will
/// be asked for.
constexpr std::string_view kGlobals[] = {
    "AIGetPlayer", "AIMV_NoAttack", "AIMV_NoAttackOutposts", "AIMV_NoAttackStrongholds",
    "AIMV_NoAttackVillages", "AIMV_NoCapture", "AIV_ArcherPercent", "AIV_ArenaHire",
    "AIV_ArenaUpgradeHires", "AIV_BuildArmy", "AIV_CombatMagic", "AIV_CounterUnits",
    "AIV_Coward", "AIV_DonateFood", "AIV_DonateGold", "AIV_DonatePop", "AIV_DruidAttach",
    "AIV_Druids", "AIV_ExcessGold", "AIV_FeedWithWagons", "AIV_GTRush", "AIV_GoAround",
    "AIV_InterruptPassing", "AIV_LogAUF", "AIV_LogArmy", "AIV_LogFeed", "AIV_LogFlee",
    "AIV_LogFoodSell", "AIV_LogFreezeArmy", "AIV_LogGetGS", "AIV_LogHeroes", "AIV_LogPlayer",
    "AIV_LogRecruit", "AIV_LogResearch", "AIV_LogRush", "AIV_LogSiege", "AIV_LogTrain",
    "AIV_LuckyExplore", "AIV_MaxAttentionPoints", "AIV_MaxBBowman", "AIV_MaxBBronzeSpearman",
    "AIV_MaxBHighlander", "AIV_MaxBJavelineer", "AIV_MaxBShieldBearer", "AIV_MaxBSwordsman",
    "AIV_MaxBVikingLord", "AIV_MaxCBerberAssassin", "AIV_MaxCJavelinThrower",
    "AIV_MaxCLibyanFootman", "AIV_MaxCMaceman", "AIV_MaxCNoble", "AIV_MaxCNumidianRider",
    "AIV_MaxCWarElephant", "AIV_MaxEAnubisWarrior", "AIV_MaxEArcher", "AIV_MaxEAxetrower",
    "AIV_MaxEGuardian", "AIV_MaxEHorusWarrior", "AIV_MaxESwordsman", "AIV_MaxGArcher",
    "AIV_MaxGAxeman", "AIV_MaxGHorseman", "AIV_MaxGSpearman", "AIV_MaxGSwordsman",
    "AIV_MaxGTridentWarrior", "AIV_MaxGWomanWarrior", "AIV_MaxIArcher", "AIV_MaxICavalry",
    "AIV_MaxIDefender", "AIV_MaxIEliteGuard", "AIV_MaxIMilitiaman", "AIV_MaxIMountaineers",
    "AIV_MaxISlinger", "AIV_MaxMilEval", "AIV_MaxMilUnits", "AIV_MaxRArcher", "AIV_MaxRChariot",
    "AIV_MaxRGladiator", "AIV_MaxRHastatus", "AIV_MaxRLiberati", "AIV_MaxRPraetorian",
    "AIV_MaxRPretorian", "AIV_MaxRPrinciple", "AIV_MaxRScout", "AIV_MaxRVelit",
    "AIV_MaxTArcher", "AIV_MaxTAxeman", "AIV_MaxTHuntress", "AIV_MaxTMaceman",
    "AIV_MaxTSwordsman", "AIV_MaxTTeutonRider", "AIV_NoRecruit", "AIV_Research", "AIV_SellFood",
    "AIV_Sleep_ES", "AIV_Sleep_GS", "AIV_Sleep_Recruit", "AIV_Sleep_SquadMonitor",
    "AIV_Sleep_TS", "AIV_SquadRecruitWait", "AIV_SquadRecruitWeight", "AIV_SquanderFoolAmount",
    "AIV_SquanderGoldAmount", "AIV_SynchApproach", "AIV_TakeItems", "AIV_TechBudget",
    "AIV_TechReserve", "AIV_TimeStrongholdDefences1", "AIV_TimeStrongholdDefences2",
    "AIV_TradeGold", "AIV_Training", "AIV_TrainingRush", "AIV_Tribute", "AIV_UpgradeBarracks",
    "AIV_UseForts", "AIV_UseItems", "AIV_UseRuins", "AIV_UseTeleports", "AIV_VillageDrain",
    "AI_ALL", "AI_ALLY", "AI_COMING", "AI_ENEMY", "AI_LEAVING", "AI_OWN", "AI_STAYING",
    "Breakpoint", "Britain", "Carthage", "ES_NONE", "ES_OutpostArmy", "ES_OutpostSellFood",
    "ES_OutpostSellGold", "ES_OutpostSendGold", "ES_Shipyard", "ES_Stronghold", "ES_Village",
    "Egypt", "GAIKACount", "GS_Capture", "GS_EnterSettlement", "GS_Guard", "GS_KillEnemies",
    "GS_NONE", "GS_Siege", "Gaul", "Germany", "GetMapRect", "GetTime", "Iberia", "ImperialRome",
    "MapSize", "MaxGAIKAPriority", "MaxSetIdx", "RepublicanRome", "SF_ADVCHOOSER", "SF_NOAI",
    "SF_PEACEFUL", "SS_Approach", "SS_ApproachWait", "SS_Attach", "SS_Capture", "SS_Catapult",
    "SS_Enter", "SS_Flee", "SS_Heal", "SS_IDLE", "SS_KillAll", "SS_Ruins", "SS_Siege",
    "SS_Train", "SS_Wait", "TS_BritishTactic", "TS_CarthageTactic", "TS_CarthageTactic2",
    "TS_EgyptTactic", "TS_GaulTactic", "TS_GaulTactic2", "TS_GermanyTactic",
    "TS_GermanyTactic2", "TS_IberianTactic", "TS_IberianTactic2", "TS_MRomeTactic",
    "TS_MRomeTactic2", "TS_NONE", "TS_RRomeTactic", "UNITFLAG_NOAI", "cBaseRuins",
    "cBaseShipyard", "cBaseTownhall", "cBaseVillage", "cBuilding", "cGate", "cHero",
    "cItemHolder", "cMilitary", "cPeasant", "cShipL", "cShipS", "cStonehenge", "cTTent",
    "cTeleport", "cWagon", "cmdcost_food", "cmdcost_gold", "cmdcost_pop", "cmdcost_stamina",
    "cmdparam", "cmdwaiting", "cripple", "curse", "gsBloodlust", "gsDivineSacrifice",
    "gsSoothingRain", "gsStarvation", "gsTribute", "gsWindOfWisdom", "healing", "hsAssault",
    "hsBattleCry", "hsCeasefire", "hsCharge", "hsConcealment", "hsDefensiveCry", "hsDiscipline",
    "hsEpicEndurance", "hsEuphoria", "hsFrenzy", "hsHealing", "hsLeadership", "hsQuickMarch",
    "hsRecovery", "hsRush", "hsSurvival", "hsTeamAttack", "hsTeamDefense", "hsVigor",
    "hsWisdom", "invisibility", "owner", "parry", "revitalize", "sneak", "teaching", "this",
};

}  // namespace

void declare_shipped_surface(HostRegistry& registry) {
  for (const Declaration& declaration : kFreeFunctions) {
    registry.declare(CallKind::free_function, declaration.name, declaration.arity);
  }
  for (const Declaration& declaration : kMembers) {
    registry.declare(CallKind::member, declaration.name, declaration.arity);
  }
}

std::span<const std::string_view> shipped_global_names() { return kGlobals; }

}  // namespace imperivm::core::script
