#!/usr/bin/env python3
"""Compile the sprite shaders and embed them in a committed C++ header.

The SDL GPU API takes shaders already in the backend's own form: SPIR-V for
Vulkan, MSL (or a metallib) for Metal, DXIL for D3D12. This project compiles
them **offline** and commits the result, so that building the engine needs a
C++ compiler and SDL3 and nothing else. See docs/engine/rendering.md.

    python3 engine/platform/shaders/pack_shaders.py

Requires `glslangValidator` (Homebrew `glslang`, Debian `glslang-tools`, or the
Vulkan SDK) on PATH. Contributors who do not touch the shaders never need it:
the generated header is checked in.

The MSL half is hand-written, not cross-compiled, and is embedded verbatim.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "generated" / "sprite_shaders.inc"

STAGES = [("sprite.vert.glsl", "vert", "kSpriteVertexSpirv"),
          ("sprite.frag.glsl", "frag", "kSpriteFragmentSpirv"),
          ("layer.frag.glsl", "frag", "kLayerFragmentSpirv")]


def compile_spirv(source: Path, stage: str) -> bytes:
    glslang = shutil.which("glslangValidator")
    if glslang is None:
        raise SystemExit(
            "glslangValidator not found. Install it (brew install glslang, "
            "apt install glslang-tools, or the Vulkan SDK) -- or leave the "
            "checked-in header alone if you did not change a shader."
        )
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "out.spv"
        subprocess.run(
            [glslang, "-V", "--target-env", "vulkan1.0", "-S", stage,
             str(source), "-o", str(out)],
            check=True,
        )
        return out.read_bytes()


def as_c_array(name: str, data: bytes) -> str:
    if len(data) % 4:
        raise SystemExit(f"{name}: SPIR-V must be a whole number of words")
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    lines = [f"inline constexpr unsigned int {name}[] = {{"]
    for i in range(0, len(words), 6):
        lines.append("    " + " ".join(f"0x{w:08x}u," for w in words[i:i + 6]))
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parts = [
        "// GENERATED by engine/platform/shaders/pack_shaders.py -- do not edit.",
        "//",
        "// Sources: sprite.vert.glsl, sprite.frag.glsl, layer.frag.glsl",
        "//                                              (SPIR-V, via glslangValidator)",
        "//          sprite.metal                        (MSL, embedded verbatim)",
        "//",
        "// Committed so that building the engine needs only a C++ compiler and SDL3.",
        "// Regenerate after changing any shader source.",
        "",
        "#pragma once",
        "",
        "namespace imperivm::platform::shaders {",
        "",
    ]

    for filename, stage, symbol in STAGES:
        spirv = compile_spirv(HERE / filename, stage)
        parts.append(as_c_array(symbol, spirv))
        parts.append("")

    msl = (HERE / "sprite.metal").read_text(encoding="utf-8")
    if ")==" in msl:
        raise SystemExit("sprite.metal contains the raw-string delimiter )==")
    parts.append('inline constexpr char kSpriteMsl[] = R"==(')
    parts.append(msl.rstrip("\n"))
    parts.append(')==";')
    parts.append("")
    parts.append("}  // namespace imperivm::platform::shaders")
    parts.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
